import Head from 'next/head'
import React from 'react'

const HeadElement = ({ subTitle }) => {
    return (
        <Head>
            <title key="title">
                {subTitle
                    ? `Tamim Enterprise ${subTitle && ' - ' + subTitle}`
                    : 'Tamim Enterprise'}
            </title>

            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo-main.png" />
        </Head>
    )
}

export default HeadElement